//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalR_SqlDependency.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mensaje
    {
        public int IdMensajes { get; set; }
        public Nullable<int> Canal { get; set; }
        public Nullable<int> Emisor { get; set; }
        public Nullable<int> Receptor { get; set; }
        public string Mensaje1 { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
